set shell := ["nu", "-c"]

RUST_LOG := env_var_or_default("RUST_LOG", "info")

exec-dbg cmd:
    let-env RUST_LOG = "{{RUST_LOG}},ikki=debug"; cargo run -- {{cmd}}

exec cmd:
    let-env RUST_LOG = "{{RUST_LOG}}"; cargo run -- {{cmd}}
